"""add full_name to users

Revision ID: 66eaf16f7e1a
Revises: c1a2b3d4e5f6
Create Date: 2026-08-14 17:08:57.162082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '66eaf16f7e1a'
down_revision: Union[str, Sequence[str], None] = 'c1a2b3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('competitors', 'notes',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('competitors', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_competitors_name'), 'competitors', ['name'], unique=False)
    op.create_index(op.f('ix_competitors_website'), 'competitors', ['website'], unique=True)
    op.alter_column('price_changes', 'old_price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    op.alter_column('price_changes', 'change_amount',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               nullable=False)
    op.alter_column('price_changes', 'change_percent',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)
    op.alter_column('price_changes', 'currency',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'IRR'::character varying"))
    op.drop_constraint(op.f('uq_price_changes_current_snapshot_id'), 'price_changes', type_='unique')
    op.drop_index(op.f('ix_price_changes_current_snapshot_id'), table_name='price_changes')
    op.create_index(op.f('ix_price_changes_current_snapshot_id'), 'price_changes', ['current_snapshot_id'], unique=True)
    op.add_column('users', sa.Column('full_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'full_name')
    op.drop_index(op.f('ix_price_changes_current_snapshot_id'), table_name='price_changes')
    op.create_index(op.f('ix_price_changes_current_snapshot_id'), 'price_changes', ['current_snapshot_id'], unique=False)
    op.create_unique_constraint(op.f('uq_price_changes_current_snapshot_id'), 'price_changes', ['current_snapshot_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('price_changes', 'currency',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False,
               existing_server_default=sa.text("'IRR'::character varying"))
    op.alter_column('price_changes', 'change_percent',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('price_changes', 'change_amount',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.NUMERIC(precision=18, scale=2),
               nullable=True)
    op.alter_column('price_changes', 'old_price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.drop_index(op.f('ix_competitors_website'), table_name='competitors')
    op.drop_index(op.f('ix_competitors_name'), table_name='competitors')
    op.alter_column('competitors', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('competitors', 'notes',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
